### ISSUE TITLE
[BUG]: Error "An image tag needs to be defined" when trying to deploy to a Demo environment

### ISSUE THREAD

**Issue by stutyr** [deliowales/helm-charts-public#23]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Chart version?

v0.0.15

### Current behaviour

I've created a values file to deploy a PHP and a Node environment based on a Values template thats been successfully used in the UAT environment.  As its not a test environment I've specified the image version in my values file using 
```
application:
   image:
      repository: myapp
      tag: "v1.4.4"
```
(I've tried the tag with & without speech marks with the same result) 
However when I run `helm install myapp . --values ./env-myapp.yaml -n myapp --dry-run` I get the error
```
Error: execution error at (tenancy/charts/microservice/templates/deployment-php.yaml:40:20): An image tag needs to be defined.
```
This also happened for the deployment-node.yaml file.

In the helper.tpl file the error seems to be generated by the line
```
{{- define "microservice.project.imageURL" -}}
  {{- printf "%s/%s:%s" (include "microservice.cloud.containerRegistryURL" .) .Values.application.image.repository (include "microservice.application.image.tag" . | required "An image tag needs to be defined.") }}
{{- end -}}
```
But I've double checked and these three values are defined.

### Expected behaviour

The chart successfully rollouts using the microservice.application.image.tag value that I have defined

### Steps to reproduce

The two key code blocks in the Values.yaml file are:
```
microservice:
  application:
    image:
      repository: deals
      tag: "1.4.1"
```

and

```
  cloud:
    provider: AWS
    environment: "demo"
```

### Anything else we need to know?

This is affecting both PHP and Node based services

**Comment by adamyaziji** [comment]
The issue is here: https://github.com/deliowales/helm-charts-public/blob/56ce4b39ed629561f1aa64bedd9ab8cdf964a49e/charts/microservice/templates/_helpers.tpl#L72

It doesn't account for any environments other than Staging-Demo or UAT (AWS) or Staging-Production (Azure).
