### ISSUE TITLE
[BUG]: no matches for kind "KongIngress"

### ISSUE THREAD

**Issue by EdwardCamilleri** [deliowales/helm-charts-public#25]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Chart version?

v0.0.16

### Current behaviour

When running a helm install, it fails to install giving the following error 

Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: resource mapping not found for name: "do-not-preserve-host" namespace: "" from "": no matches for kind "KongIngress" in version "configuration.konghq.com/v1"
ensure CRDs are installed first

### Expected behaviour

I would expect the install to run and complete without failing

### Steps to reproduce

running helm install notification . -f demo-west-values.yaml -n notification --dry-run

**Comment by adamyaziji** [comment]
@EdwardCamilleri 

> ensure CRDs are installed first

Has Kong been deployed to the cluster? The Kong CRDs need to be installed as the resource `KongIngress` doesn't exist at the moment so the chart fails. I dont believe this is an issue with the chart itself
